{% set name = "dpdata" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1a65041a459c440cb412c1020a430520c1affed81daefc746a8f9f4c021eb7e
  patches:
    - version.diff

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - numpy
  run:
    - python >=3.5
    - {{ pin_compatible('numpy') }}
    - monty

test:
  imports:
    - dpdata

about:
  home: https://github.com/deepmodeling/dpdata
  license: LGPL-3.0
  license_family: LGPL
  summary: 'Manipulating DeePMD-kit, VASP and LAMMPS data formats'
  doc_url: https://github.com/deepmodeling/dpdata
  dev_url: https://github.com/deepmodeling/dpdata

extra:
  recipe-maintainers:
    - njzjz
