{% set name = "dpdata" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4cc2e650201bd71b854da21c561d60c0027e1c8c70a6d57b1c364db4a28a2fcf

build:
  number: 0
  noarch: python
  script: "SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - numpy >=1.14.3
    - monty

test:
  imports:
    - dpdata

about:
  home: https://github.com/deepmodeling/dpdata
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Manipulating DeePMD-kit, VASP and LAMMPS data formats'
  doc_url: https://github.com/deepmodeling/dpdata
  dev_url: https://github.com/deepmodeling/dpdata

extra:
  recipe-maintainers:
    - njzjz
