{% set name = "dpdata" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d04123ed158be9cb75fb0feedcbe9c93a63638605982c75eff0b0f254388ef19

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - numpy >=1.14.3
    - monty

test:
  imports:
    - dpdata

about:
  home: https://github.com/deepmodeling/dpdata
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Manipulating DeePMD-kit, VASP and LAMMPS data formats'
  doc_url: https://github.com/deepmodeling/dpdata
  dev_url: https://github.com/deepmodeling/dpdata

extra:
  recipe-maintainers:
    - njzjz
