travis:
  secure:
    BINSTAR_TOKEN: AlifxfDuOtpcgjU9YSJbRLGDA6sFJRnD4t6mAPQQ3SfDCsGjGcG022/yKRqptJhtfk7/P88ePKCRvpLMg4ka3vzkfAL+MfJ8k8DsvybUNb5UjO3iVdpeCAuKh2nju8f3V40QTpP1xtwlldW7RrGoV/4ziSQYNXG2+VSDbXFFcZvD7W1YyavZ91IJCVrejfdIdOzGefiXhyOwzPl7DX8xZ41wOztqKCrYVJkU5nJCdziY0VOA5NM8sHcgIO6k6Dpd2JEFTbJBqKpeGSN6dADhOorQyJWPaQDSYY7pr3Ykfnzt6R5NaJJEssIVqwldKqW7rwqcPOyEf8gm3il6yvXRpYWQsYBS/yWw9GxG2luBlsAxPBFlREGCwVQFTymO2BetDwBS/u18OEX/u64eAiJdNVnyC8c1LbsWlg1rufAuXWAs1Nf7skNjSstql4sAxqjZCnOhqWEt6ivAcPzTGo+EMk7offvqxMev9F1cDuZP5zOn2wG88gWWEw4Hmvp6G1iShmap4la5TOxuMZFLW1XIoGs8RJQ9af39NFOlSWvHgatf+zOttzoy1He1NEbEmxHZIq31lAxKMOMcKOARgcd/P7jNqXjFe3Ks9v696MD4w3kCp0exCls7QjbGxCOYfYBTyA4u3jXkykw6K6VhLUlpJNcRBP1axyoizIpPLeY3A/g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
